# Generated by Django 4.0.6 on 2022-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_student_email_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCountStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
