# Generated by Django 4.0.6 on 2022-08-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
